/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import model.Consulta;
import model.dao.AnimalDAO;
import model.dao.TutorDAO;
import model.dao.VeterinarioDAO;
import model.Animal;
import model.Tutor;
import model.Veterinario;
/**
 *
 * @author bruna
 */
public class CadastroConsultaJD extends javax.swing.JDialog {
    
    AnimalDAO daoAnimal;
    VeterinarioDAO daoVeterinario;
    TutorDAO daoTutor;
    
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");
    

    private Consulta consulta;
    /**
     * Creates new form CadastroConsultaJD
     */
    public CadastroConsultaJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        daoAnimal = new AnimalDAO();
        daoVeterinario = new VeterinarioDAO();
        daoTutor = new TutorDAO();
        
        loadAnimais();
        loadVeterinarios();
        loadTutores();
        
        txtDataConsulta.setText(LocalDateTime.now().format(formatter));
        
    }
    public void loadAnimais(){
        for(Animal obj: daoAnimal.listaAnimais()){
            cmbAnimal.addItem(obj);
        }
    }
    
    public void loadVeterinarios(){
        for(Veterinario obj: daoVeterinario.listaVeterinarios()){
            cmbVeterinario.addItem(obj);
        }
    }
    
    public void loadTutores(){
        for(Tutor obj: daoTutor.listaTutores()){
            cmbTutor.addItem(obj);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDataConsulta = new javax.swing.JLabel();
        lblAnimal = new javax.swing.JLabel();
        lblVeterinario = new javax.swing.JLabel();
        lblTutor = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        txtDataConsulta = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cmbAnimal = new javax.swing.JComboBox<>();
        cmbVeterinario = new javax.swing.JComboBox<>();
        cmbTutor = new javax.swing.JComboBox<>();
        txtValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Consulta");

        lblDataConsulta.setText("Data Consulta");

        lblAnimal.setText("Animal");

        lblVeterinario.setText("Veterinário");

        lblTutor.setText("Tutor");

        lblValor.setText("Valor");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDataConsulta)
                            .addComponent(lblVeterinario)
                            .addComponent(lblAnimal)
                            .addComponent(lblTutor)
                            .addComponent(lblValor))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar))
                            .addComponent(cmbAnimal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbVeterinario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTutor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtValor, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtDataConsulta)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataConsulta)
                    .addComponent(txtDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnimal)
                    .addComponent(cmbAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVeterinario)
                    .addComponent(cmbVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTutor)
                    .addComponent(cmbTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try{
            if(consulta == null);
                consulta = new Consulta();
                
            double valor = Double.parseDouble(txtValor.getText()
                    .replace(",", "."));
            LocalDateTime dataConsulta = LocalDateTime.parse(txtDataConsulta.getText(), formatter);
            
            consulta.setValor(valor);
            consulta.setData(dataConsulta);
            consulta.setAnimal((Animal)cmbAnimal.getSelectedItem());
            consulta.setVeterinario((Veterinario)cmbVeterinario.getSelectedItem());
            consulta.setTutor((Tutor)cmbTutor.getSelectedItem());
            consulta.getDescricao();
            
            daoAnimal.persist(consulta.getAnimal());
            
            this.dispose();
            
        }catch(NumberFormatException e){
            consulta = null;
            JOptionPane.showMessageDialog(this, "Valor inválido. Digite um valor válido.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (DateTimeParseException e) {
            consulta = null;
            JOptionPane.showMessageDialog(this, "Data inválida. Use o formato: dd-MM-yyyy HH:mm", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            consulta = null;
            JOptionPane.showMessageDialog(this, "Erro ao salvar consulta: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                CadastroConsultaJD dialog = new CadastroConsultaJD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Animal> cmbAnimal;
    private javax.swing.JComboBox<Tutor> cmbTutor;
    private javax.swing.JComboBox<Veterinario> cmbVeterinario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAnimal;
    private javax.swing.JLabel lblDataConsulta;
    private javax.swing.JLabel lblTutor;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblVeterinario;
    private javax.swing.JTextField txtDataConsulta;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    public Consulta getConsulta(){
        return consulta;
    }
    
    public void setConsulta(Consulta consulta){
        this.consulta = consulta;
        txtDataConsulta.setText(consulta.getData().format(formatter));
        txtValor.setText(""+consulta.getValor());
        cmbAnimal.setSelectedItem(consulta.getAnimal());
        cmbVeterinario.setSelectedItem(consulta.getVeterinario());
        cmbTutor.setSelectedItem(consulta.getTutor());
    }
}
