/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author bruna
 */
public class PrincipalJF extends javax.swing.JFrame {
   

    /**
     * Creates new form PrincipalJF
     */
    public PrincipalJF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miVeterinario = new javax.swing.JMenuItem();
        miAnimal = new javax.swing.JMenuItem();
        miTutor = new javax.swing.JMenuItem();
        miConsulta = new javax.swing.JMenu();
        miTelaConsulta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastro");

        miVeterinario.setText("Veterinario");
        miVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVeterinarioActionPerformed(evt);
            }
        });
        jMenu1.add(miVeterinario);

        miAnimal.setText("Animal");
        miAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAnimalActionPerformed(evt);
            }
        });
        jMenu1.add(miAnimal);

        miTutor.setText("Tutor");
        miTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTutorActionPerformed(evt);
            }
        });
        jMenu1.add(miTutor);

        jMenuBar1.add(jMenu1);

        miConsulta.setText("Consulta");

        miTelaConsulta.setText("Agendar Consulta");
        miTelaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTelaConsultaActionPerformed(evt);
            }
        });
        miConsulta.add(miTelaConsulta);

        jMenuBar1.add(miConsulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVeterinarioActionPerformed
        ListaVeterinariosJF telaVeterinario = new ListaVeterinariosJF();
        telaVeterinario.setVisible(true);
    }//GEN-LAST:event_miVeterinarioActionPerformed

    private void miAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAnimalActionPerformed
        ListaAnimaisJF telaAnimal = new ListaAnimaisJF();
        telaAnimal.setVisible(true);
    }//GEN-LAST:event_miAnimalActionPerformed

    private void miTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTutorActionPerformed
        ListaTutoresJF telaTutor = new ListaTutoresJF();
        telaTutor.setVisible(true);
    }//GEN-LAST:event_miTutorActionPerformed

    private void miTelaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTelaConsultaActionPerformed
        ListaConsultasJF telaConsultas= new ListaConsultasJF();
        telaConsultas.setVisible(true);
    }//GEN-LAST:event_miTelaConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJF().setVisible(true);
            }
        });    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miAnimal;
    private javax.swing.JMenu miConsulta;
    private javax.swing.JMenuItem miTelaConsulta;
    private javax.swing.JMenuItem miTutor;
    private javax.swing.JMenuItem miVeterinario;
    // End of variables declaration//GEN-END:variables
}
